### ISSUE TITLE
API elkészítése

### ISSUE THREAD

**Issue by buviktor** [buviktor/Project_MK#30]
URL-ek és lekérdezések elkészítése

**Comment by Tamasd9182** [comment]
Api a felhasználókhoz:
/user/all/
/user/posts/
/user/post/
/user/person/
/signup

**Comment by Tamasd9182** [comment]
Api az Admin-hoz:
/admin/stat/
/admin/users/

**Comment by Tamasd9182** [comment]
Api felhasználók/admin:
/login
/categories
/user/person/  (delete)
